version: "3"

services:
  web:
    image: ${DOCKERHUB_IMAGE}
    container_name: ${APP_NAME}
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
