version: "3"

services:
  web:
    image: ${DOCKERHUB_IMAGE}
    container_name: ${APP_NAME}
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - nginx-proxy-network
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
