name: Deploy

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  # Stage 1: Build and push Docker image to private registry
  build-and-push:
    name: Build & Push Image
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Authenticate with Docker Hub
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push image
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: . # Build context
          push: true # Push after build
          tags: ${{ vars.DOCKERHUB_IMAGE_TAG }}

  # STAGE 2: Deploy to production server
  deploy:
    name: Deploy to Production
    needs: [build-and-push] # Requires successful build first
    runs-on: ubuntu-latest
    env:
      APP_DIR: "/var/www/${{ vars.LOCATION }}"

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Configure SSH connection
      - name: Setup SSH
        run: |
          echo "Setting up SSH connection to port ${{ vars.SSH_PORT }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "Adding host key for ${{ vars.SSH_HOST }}:${{ vars.SSH_PORT }}"
          ssh-keyscan -p ${{ vars.SSH_PORT }} -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          echo "SSH setup complete"

      # Step 3: Copy the docker compose file and Makefile to the server
      - name: Upload Auxiliary Files to Server
        run: |
          echo "Uploading files to server on port ${{ vars.SSH_PORT }}"
          scp -P ${{ vars.SSH_PORT }} -i ~/.ssh/id_ed25519 docker-compose.prod.yml Makefile ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:${{ env.APP_DIR }}
          echo "File upload complete"

      # Step 4: Execute deployment commands on server
      - name: Run Deployment
        run: |
          echo "Starting deployment process on port ${{ vars.SSH_PORT }}"
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} << 'EOF'
            set -euo pipefail # Exit on error + if any command fails
            cd "${{ env.APP_DIR }}"
            
            echo "Current directory: $(pwd)"
            echo "Files in directory:"
            ls -la
            
            # 2. Login to Docker Hub
            echo "Logging into Docker Hub"
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
              -u "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin
            
            # 3. Stop and remove old containers
            echo "Stopping and removing old containers"
            make deploy-down
            
            # 4. Cleanup unused images
            echo "Pruning Docker images and builder cache"
            make deploy-prune
            
            # 5. Pull latest images
            echo "Pulling latest images"
            make deploy-pull

            # 6. Start new containers
            echo "Starting new containers"
            make deploy-up
            
            echo "Successfully deployed: ${{ vars.DOCKERHUB_IMAGE_TAG }}"
            
            # Extra logs
            echo "Docker Compose status:"
            docker compose ps
            echo "Recent logs:"
            docker compose logs --tail=50
          EOF
