# This workflow tests that SSH connection via GitHub Actions is working for your server.
# This process will be used in the deploy workflow so this is useful to test.

# Necessary repository variables:
# SSH_HOST: The IP/hostname of your server
# SSH_PORT: The SSH port of your server
# SSH_USER: The SSH user of your server

# Necessary repository secrets:
# SSH_PRIVATE_KEY: Your server's private key

name: Test SSH

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Configure SSH connection
      - name: Setup SSH
        run: |
          echo "Setting up SSH connection to port ${{ vars.SSH_PORT }}"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          echo "Adding host key for ${{ vars.SSH_HOST }}:${{ vars.SSH_PORT }}"
          ssh-keyscan -p ${{ vars.SSH_PORT }} -H ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts

          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          echo "SSH setup complete"

      # Step 2: Test SSH connection
      - name: Test SSH connection
        run: |
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "echo 'GitHub Actions SSH is working for the SSH user.'"
